### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by ns-rse** [ns-rse/git-collaboration#66]

**Comment by Robadob** [comment]
Creating a virtual environment, you can install pip at env creation by specifying it alongside python=3.11, saves a 3rd command.

**Comment by ns-rse** [comment]
> Creating a virtual environment, you can install pip at env creation by specifying it alongside python=3.11, saves a 3rd command.

I checked this yesterday morning and found `pip` is installed as a dependency automatically so will remove it completely.
