### ISSUE TITLE
Hooks

### ISSUE THREAD

**Issue by ns-rse** [ns-rse/git-collaboration#70]

**Comment by Robadob** [comment]
pull before push, entire section is a callout with no other content????

**Comment by fredsonnenwald** [comment]
I think this also need relating back to what researchers could get out of this

**Comment by Robadob** [comment]
```
conda create -n python-maths python=3.11
conda activate python-maths
conda install pre-commit
```

Could be

```
conda create -n python-maths python=3.11 pre-commit
conda activate python-maths
```

**Comment by Robadob** [comment]
Something is wrong with Challenge 7, the body title/text appears asthough it's the solution.

**Comment by fredsonnenwald** [comment]
Call out for cron, are researchers likely enough to be using linux to justify a single OS call out?
