### ISSUE TITLE
Please check you have applied the changes specified in fair4rs-lesson-setup

### ISSUE THREAD

**Issue by tdjames1** [ns-rse/git-collaboration#88]
Please could you check that you have made suitable adjustments to the following files (links to how they should look):
+ [x] [Acknowledgements](https://romain-thomas-shef.github.io/FAIR_Management_plan/acknowledgements.html) page
This training has been created by the RSE team at the University of Sheffield, supported by the Department of Computer Science and IT services.
+ [x] [CODE OF CONDUCT](https://romain-thomas-shef.github.io/FAIR_Management_plan/CODE_OF_CONDUCT.html)
As contributors and maintainers of this project, we pledge to follow the University of Sheffield Research Software Engineering Code of Conduct.
Instances of abusive, harassing, or otherwise unacceptable behavior may be reported by following our reporting guidelines.
+ [x] [CONTRIBUTING](https://github.com/Romain-Thomas-Shef/FAIR_Management_plan/blob/main/CONTRIBUTING.md)
Adjusted to remove references to The Carpentries.
+ [x] [LICENSE](https://romain-thomas-shef.github.io/FAIR_Management_plan/LICENSE.html)
Acknowledges development from The Carpentries template with indication of changes made.

**Comment by ns-rse** [comment]
Site/repository appears to have been renamed, using the files from [Romain-Thomas-Shef/FAIR24RS_Software_lifecycle_planning](https://github.com/Romain-Thomas-Shef/FAIR24RS_Software_lifecycle_planning/).
